name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
      - run: npm ci
      - run: npm run deploy -- --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          CERTIFICATE_ARN: ${{ vars.CERTIFICATE_ARN }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
