name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.2.0
      - run: npm ci
      - run: npm run deploy -- --require-approval never
        env:
          API_PATH: ${{ secrets.API_PATH }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          CERTIFICATE_ARN: ${{ vars.CERTIFICATE_ARN }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          PAGERDUTY_DISABLE: ${{ vars.PAGERDUTY_DISABLE }}
          PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
          PARTITION_KEY: ${{ vars.PARTITION_KEY }}
          TEMPERATURE_LIMIT: ${{ vars.TEMPERATURE_LIMIT }}
          TIME_LIMIT: ${{ vars.TIME_LIMIT }}
